### PR TITLE
feat: updating brand api

### PR DESCRIPTION
**Pull request by Lucca-C**
Updated brand API in Android SDK, followed JS SDK pattern.

### CODE REVIEW

**Comment by joao-conde** [comment]
@Lucca-C  CI is failing, fix it before opening the PR

**Comment by joao-conde** [comment]
@Lucca-C title of the PR should be in the format "feat: brand API feature parity with JS SDK"

**Review by joao-conde — CHANGES_REQUESTED** [review]
Update the changelog

**Comment by hugo-gomes** [comment]
@joao-conde @Lucca-C is this still relevant?

**Comment by joao-conde** [comment]
@hugo-gomes  some relevant code can be extracted, I will work on it

**Comment by hugo-gomes** [comment]
tagged as `no-closing`

@joao-conde let's pick up this subject on the 24th then.

**Comment by hugo-gomes** [comment]
@joao-conde @Lucca-C should we close this or is this a WIP?

**Comment by joao-conde** [comment]
@hugo-gomes WIP, this needs some code removed. When I have the time I will help Lucca with it

**Comment by hugo-gomes** [comment]
@joao-conde was this discarded?

**Comment by hugo-gomes** [comment]
Ok, deleting the branch then

**Pull request closed without merging**
