### PR TITLE
Grammar fixed

### PR DESCRIPTION
**Pull request by herou**
I fixed a small thing in the readme.

### CODE REVIEW

**Review by joamag — APPROVED** [review]

**Comment by herou** [comment]
@joamag I do not see many issues open, are you open for contributors?

**Comment by joamag** [comment]
> @joamag I do not see many issues open, are you open for contributors?

Yes, of course, feel free to contribute!

**Comment by herou** [comment]
@joamag Would be easier if there would be some initial issues raised.

**Comment by joamag** [comment]
> @joamag Would be easier if there would be some initial issues raised.

I'll try to find out what's more urgent and open issues. Thank you!

**Comment by herou** [comment]
@joamag Any news?

**Comment by joamag** [comment]
> @joamag Any news?

Not yet, but you can start by taking a look at the [RIPE SDK](https://github.com/ripe-tech/ripe-sdk) project (which is the Javascript implementation) to find the feature level that we want to achieve with the Android SDK

**Pull request merged**
